version: "3.8"

services:
  qdrant:
    image: docker.repo.de.service.retloc/qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    restart: always
    volumes:
      - qdrant_data:/qdrant/storage  # Mount a volume for persistent storage

 # email-ai-api:
 #   build: .
 #   container_name: email-ai-api
 #   ports:
 #     - "5000:5000"
 #   depends_on:
 #     - qdrant
 #   restart: always

volumes:
  qdrant_data:
    driver: local
